config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :sessions, only:[:new, :create, :destroy]
  resources :tasks
  resources :labels
  namespace :admin do
    resources :users
  end
  resources :users, only:[:new, :create,:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_label
  has_many :tasks, through: :task_label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :labels, through: :task_labels
  validates :title, presence:true
  validates :content, presence:true
  enum priority: {low: 0, middle: 1, high:2, top:3}
  scope :expired, -> {order(expired_at: :desc)}
  scope :priority, -> {order(priority: :desc)}
  # scope :search_label, -> (label){where('[id = ?]',label)}
  scope :search_title, -> (title){where('title Like ?',"%#{title}%")}
  scope :search_status, -> (status){where('status = ?',status)}
  scope :search_all,-> (title,status){where('title Like ? and status = ?',"%#{title}%",status)}
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true,
  format:{with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  before_validation{email.downcase!}
  has_secure_password
  before_destroy do
      if self.admin? && User.where(admin:true).count == 1
          throw :abort
      end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action:require_admin
  before_action:access_user
  before_action:set_user, only:[:edit,:update,:destroy,:show]

  def index
    @users = User.all.includes(:tasks)
  end

  def new
      @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path,notice: "作成しました"
    else
      render 'new'
    end
  end

  def destroy
    if current_user != @user
      @user.destroy
      redirect_to admin_users_path, notice: "削除しました"
    else
      redirect_to admin_users_path, notice: "このユーザーは削除できません"
    end
  end

  def edit
  end

  def update
     if @user.update(user_params)
       redirect_to admin_users_path,notice: "編集しました"
     end
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

  def require_admin
      raise Forbidden unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def access_user
      redirect_to new_session_path, notice: "ログインが必要です" unless session[:user_id] != nil
  end

class Forbidden < ActionController::ActionControllerError
end

  rescue_from Forbidden, with: :rescue403

  private

  def rescue403(e)
    @exception = e
      render 'admin/forbbiden' , status:403
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
      redirect_to tasks_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path
      flash[:notice] = "ログインしました"
    else
      flash.now[:danger]
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice]
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :access_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :edit_task, only: [:show, :edit, :update, :destroy]
  PER = 5
# require byebug
  def index
    if params[:key]
        @tasks = User.find(params[:key]).tasks.all.page(params[:page]).per(PER)
      elsif params[:sort_expired]
        @tasks = current_user.tasks.all.expired.page(params[:page]).per(PER)
      elsif params[:sort_priority]
        @tasks =  current_user.tasks.all.priority.page(params[:page]).per(PER)
      elsif params[:task] == nil
        @tasks =  current_user.tasks.page(params[:page]).per(PER)
      elsif params[:task][:label_id].present?
        labels =  TaskLabel.where('label_id = ?',params[:task][:label_id]).pluck(:task_id)
        tasks = current_user.tasks.find(labels)
        @tasks = Kaminari.paginate_array(tasks).page(params[:page]).per(PER)
      # elsif params[:task][:label_id].present?
      # labels =  TaskLabel.where('label_id = ?',params[:task][:label_id]).pluck(:task_id)
      # tasks = current_user.tasks.search_label(labels)
      # @tasks = Kaminari.paginate_array(tasks).page(params[:page]).per(PER)

      elsif params[:task][:title].present? && params[:task][:status].blank?
        @tasks =  current_user.tasks.search_title(params[:task][:title]).page(params[:page]).per(PER)
      elsif params[:task][:status].present? && params[:task][:title].blank?
        @tasks =  current_user.tasks.search_status(params[:task][:status]).page(params[:page]).per(PER)
      elsif params[:task][:title].present? && params[:task][:status].present?
        @tasks =  current_user.tasks.search_all(params[:task][:title],params[:task][:status]).page(params[:page]).per(PER)
      elsif params[:task][:search] == "true"
        @tasks =  current_user.tasks.all.page(params[:page]).per(PER)
    end
  end

  def new
    # @task = Task.new
     @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "作成しました"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def show
    @labels = @task.labels
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "削除しました"
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title,:content,:expired_at,:status,:priority,:user_id, label_ids:[])
  end

  def edit_task
      if current_user.id != @task.user_id
        flash[:notice] = "権限がありません"
        redirect_to tasks_path
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:access_user, only:[:show]
  before_action:set_user, only:[:show]

  def new
    if logged_in?
      redirect_to tasks_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] =  @user.id
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    redirect_to tasks_path unless current_user == @user || current_user.admin == true
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end

def logged_in?
  current_user.present?
end
end

app/views/admin/users/edit.html.erb
<h1>ユーザー<%= t('view.edit') %></h1>
<%= form_with(model: [:admin,@user],local: true) do |f| %>
<table  class="new_table">
  <tr>
  <th><%= User.human_attribute_name(:name) %></th>
  <td><%= f.text_field :name %></td>
  </tr>
  <tr>
  <th><%= User.human_attribute_name(:email)   %></th>
  <td><%= f.text_field:email %></td>
  </tr>
  <tr>
  <th><%= User.human_attribute_name(:admin)   %></th>
  <td><%= f.select :admin,[true,false] %></td>
  </tr>
</table>
<%= f.submit %>
<%= link_to t('view.back'), :back %>
<% end %>

app/views/admin/users/index.html.erb
<h1>ユーザー管理</h1>
  <p class="btn btn-secondary"><%= link_to "ユーザー作成", new_admin_user_path %></p>
  <table class = "table_style">
    <div class = "row">
    <tr　class= "col-mid-12">
      <th><%= User.human_attribute_name(:id) %></th>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= User.human_attribute_name(:admin) %></th>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <th><%= User.human_attribute_name(:updated_at) %></th>
      <th><%= t('view.count') %></th>
      <th></th>
      <th></th>
      <th></th>
      </tr>
    </div>
<% @users.all.includes(:tasks).each do |user| %>
  <div class="row">
    <tr class="col-mid-12">
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin %></td>
      <td><%= user.created_at.strftime("%Y/%m/%d") %></td>
      <td><%= user.updated_at.strftime("%Y/%m/%d") %></td>
      <td><%= user.tasks.count %></td>
      <td class="btn btn-secondary"><%= link_to t('view.show'),tasks_path(key: user.id) %></td>
      <td class="btn btn-secondary"><%= link_to t('view.edit'),edit_admin_user_path(user.id) %></td>
      <td class="btn btn-secondary"><%= link_to t('view.delete'),admin_user_path(user.id),method: :delete %></td>
    </tr>
  </div>
  <% end %>
  </table>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>
<% if @user.errors.any? %>
<div id = "error_explanation">
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</div>
<% end %>


<%= form_with(model:@user,local:true,url:admin_users_path) do |f| %>
<table class="new_table">
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:name) %></th>
  <td><%= f.text_field :name %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:email) %></th>
  <td><%= f.email_field :email %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:password) %></th>
  <td><%= f.password_field :password %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:password_confirmation) %></th>
  <td><%= f.password_field :password_confirmation %></td>
  </tr>
</table>
<%= f.submit %>
<%= link_to t('view.back'), :back %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div class="container">　
  <header class = "row">

    <% if logged_in? && current_user.admin == true %>
    <ul class ="col-md-12">
      <li><%= link_to "Logout" ,session_path(current_user.id),method: :delete %></li>
      <li><%= link_to "ユーザー管理",admin_users_path %></li>
    </ul>
    <% elsif logged_in? %>
    <ul class ="col-md-12">
      <li><%= link_to "Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Logout" ,session_path(current_user.id),method: :delete %></li>
      <li><%= link_to t('view.create'),new_task_path %></li>
      <li><%= link_to t('view.index'),tasks_path %></li>
    </ul>
    <% else %>
    <ul class ="col-md-12">
      <li><%= link_to "Sign up",new_user_path %></li>
      <li><%= link_to "Login", new_session_path %></li>
    </ul>
    <% end %>

  </header>

  <body>
      <% flash.each do |key,value| %>
        <%= content_tag(:div,value,class:"#{key}") %>
      <% end %>
    <%= yield %>
  </body>
    </div>
</html>

app/views/tasks/_form.html.erb
  <%= form_with(model: @task,local: true) do |form| %>
    <% if @task.errors.any? %>
      <div>
        <% @task.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>

<table  class="new_table">
  <tr>
  <th><%= form.label t('view.title') %></th>
  <td><%= form.text_field :title %></td>
  </tr>
  <tr>
  <th><%= form.label t('view.content') %></th>
  <td><%= form.text_area :content %></td>
  </tr>
  <tr>
  <th><%= form.label t('view.expired_at')  %></th>
  <td><%= form.date_field :expired_at %></td>
  </tr>
  <tr>
  <th><%= form.label t('view.status') %></th>
  <td><%= form.select :status,[nil,
    [t('view.not_start'),t('view.not_start')],
    [t('view.start'),t('view.start')],
    [t('view.finish'),t('view.finish')]]
      %></td>
  </tr>
  <tr>
  <th><%= form.label t('view.priority') %></th>
  <td><%= form.select :priority, Task.priorities_i18n.keys.map{|k| [Task.priorities_i18n[k], k]} %></td>
  </tr>
</table>
<div>
<% Label.all.each do |label| %>
<%= form.check_box :label_ids, {multiple: true, checked: label[:checked], disable: label[:disable] , include_hidden: false}, label[:id] %>
<%= label.tag %>
<% end %>
</div>

  <%= form.submit %>
  <%= link_to t('view.back'), :back %>
  <% end %>

app/views/tasks/edit.html.erb
<h1><%= t('view.edit') %></h1>
  <%= render 'form' %>

app/views/tasks/index.html.erb
<h1><%= t('view.index') %></h1>
<%= form_with(model: Task.new,local: true,method: :get,url:tasks_path) do |form| %>
<table class = "table_style">
    <tr class="row">
    <div class = "col-mid-12">
    <th><%= form.label t('view.title') %></th>
    <td><%= form.text_field :title %></td>
    <th><%= form.label t('view.status') %></th>
    <td><%= form.select :status,[ nil,
                                  [t('view.not_start'),t('view.not_start')],
                                  [t('view.start'),t('view.start')],
                                  [t('view.finish'),t('view.finish')]]  %></td>
    <td><%= form.hidden_field :search, value:'true' %></td>
    <th><%= form.label :label %></th>
    <td><%= form.select :label_id,[ nil,
                                  [t('view.label1'),1],
                                  [t('view.label2'),2],
                                  [t('view.label3'),3],
                                  [t('view.label4'),4],
                                  [t('view.label5'),5]] %></td>
  <td><%= form.submit t('view.search') %></td>
    <td class="btn btn-secondary"><%= link_to "終了期限でソートする", tasks_path(sort_expired: 'true') %></td>
    <td class="btn btn-secondary"><%= link_to "優先度でソートする", tasks_path(sort_priority: 'true') %></td>
    </div>
    </tr>
</table>
<% end %>

  <table class = "table_style">
    <div class = "row">
    <tr　class = "col-mid-12">
    <th><%= t('view.title') %></th>
    <th><%= t('view.content') %></th>
    <th><%= t('view.created_at') %></th>
    <th><%= t('view.expired_at') %></th>
    <th><%= t('view.status') %></th>
    <th><%= t('view.priority') %></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    </tr>
    </div>
  <% @tasks.each do |task| %>
  <div class="row">
    <tr class="col-mid-12">
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.created_at.strftime("%Y/%m/%d") %></td>
      <td><%= task.expired_at.strftime("%Y/%m/%d") %></td>
      <td><%= task.status %></td>
      <td><%= task.priority_i18n %></td>
      <td class="btn btn-secondary"><%= link_to t('view.show'),task_path(task.id) %></td>
      <td class="btn btn-secondary"><%= link_to t('view.edit'),edit_task_path(task.id) %></td>
      <td class="btn btn-secondary"><%= link_to t('view.delete'),task_path(task.id) ,method: :delete %></td>
    </tr>
  </div>
  <% end %>
  </table>

  <%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1><%= t('view.create') %></h1>
  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= t('view.show') %></h1>
  <table  class="new_table">

    <tr><th><%= t('view.title') %></th>
      <td><%= @task.title %></td></tr>
    <tr><th><%= t('view.content') %></th>
      <td><%= @task.content %></td></tr>
    <tr><th><%= t('view.created_at') %></th>
      <td><%= @task.created_at.strftime("%Y-%m-%d") %></td></tr>
    <tr><th><%= t('view.expired_at') %></th>
      <td><%= @task.expired_at.strftime("%Y-%m-%d") %></td></tr>
      <% if @labels.present? %>
      <tr>
        <th><%= :label %></th>
          <% @labels.each do |label| %>
              <td class="btn btn-secondary"><%= label.tag %></td>
          <% end %>
      </tr>
        <% end %>
  </table>
  <%= link_to t('view.back'), :back %>

app/views/users/new.html.erb
<h1>ユーザー作成</h1>
<% if @user.errors.any? %>
<div id = "error_explanation">
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</div>
<% end %>


<%= form_with(model:@user,local:true) do |f| %>
<table class="new_table">
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:name) %></th>
  <td><%= f.text_field :name %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:email) %></th>
  <td><%= f.email_field :email %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:password) %></th>
  <td><%= f.password_field :password %></td>
  </tr>
  <tr class="col-mid-3">
  <th><%= f.label User.human_attribute_name(:password_confirmation) %></th>
  <td><%= f.password_field :password_confirmation %></td>
  </tr>
</table>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<table class="new_table">
  <tr>
  <th><%= t('view.name') %></th>
  <td><%= @user.name %></td>
  </tr>
  <tr>
  <th><%= t('view.email')  %></th>
  <td><%= @user.email %></td>
  </tr>
</table>